<?php
$lipsum = <<<EOT
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus neque nibh, tristique sit amet massa et, condimentum consectetur arcu. Quisque pharetra mauris enim, vel scelerisque nunc gravida vitae. Ut aliquet sit amet lectus at congue. Etiam consectetur at justo quis sodales. Nulla rhoncus varius massa, quis gravida ante efficitur sit amet. Curabitur eleifend volutpat tellus nec pharetra. Nunc eleifend tortor ut fringilla tincidunt. Morbi blandit id lacus eu elementum. Suspendisse sit amet eleifend dui. Fusce sed placerat ante, tincidunt gravida lacus.

Sed eget enim a nulla tincidunt tempus ut quis tellus. Etiam in rutrum ligula, vel dapibus odio. In elementum mauris sed turpis lacinia egestas. Sed lacinia nibh ac placerat porta. Fusce vel erat ac diam sollicitudin luctus a vitae leo. Donec non leo eros. Nam tincidunt condimentum ligula ut efficitur. Aliquam vitae pellentesque lectus. Curabitur eget sapien dolor.

Vivamus eleifend metus id ultricies ultricies. Aliquam vitae volutpat ipsum. Nulla fringilla lectus eget felis posuere sodales. Nulla imperdiet metus et faucibus lobortis. Nulla non pretium elit, et pulvinar erat. Nullam vel sagittis neque, id gravida eros. Maecenas ipsum turpis, rutrum at nibh in, elementum pretium tellus. Curabitur gravida elit ac sapien finibus accumsan. Ut a libero gravida, blandit lacus sit amet, pellentesque nunc. Curabitur aliquam vestibulum lobortis.

Nunc tincidunt gravida tincidunt. Ut in felis scelerisque, vulputate leo at, iaculis nunc. In porta nibh diam, ut rhoncus eros suscipit nec. Quisque consequat massa vitae dui maximus, ut mollis urna ultricies. Quisque quis tincidunt purus, in rutrum justo. Donec vehicula molestie lorem, sed aliquet nisl consequat eu. Mauris risus leo, placerat imperdiet augue ac, auctor condimentum odio. Cras placerat sagittis porttitor. Donec commodo eu nisi in blandit.

Maecenas interdum fringilla eros, maximus faucibus purus. Sed fermentum lacus vitae purus congue, in lobortis arcu finibus. Duis molestie pellentesque mattis. Fusce quis leo non sapien tristique auctor. Integer hendrerit, neque non interdum rutrum, dui tortor congue leo, in tincidunt nibh neque vitae sapien. Proin consequat risus pellentesque mi sollicitudin scelerisque. Cras tempus interdum mi, vitae tincidunt neque. Vivamus sed lorem eget justo sollicitudin sollicitudin ut non turpis. In felis turpis, dictum ac odio non, placerat sodales ipsum. Vivamus ut eros sapien. Morbi pulvinar mattis nulla malesuada imperdiet. Fusce convallis est non auctor aliquet.

Vestibulum dignissim in sapien sed luctus. Etiam sagittis sodales libero ut bibendum. Suspendisse gravida erat non magna tempor, at pharetra dolor rutrum. Fusce ac ultrices dolor. Pellentesque ligula turpis, lacinia eu sagittis ac, mollis eget eros. In vel enim et nisl sodales auctor. Aenean accumsan massa at laoreet posuere. Nulla facilisi. Morbi ac condimentum enim, tempor vestibulum sapien. Nunc faucibus mauris id ultricies pulvinar. Donec euismod posuere pellentesque. Etiam pellentesque tincidunt metus ut congue. Donec sodales dolor vel sagittis finibus.

Duis leo ipsum, vulputate vitae arcu sit amet, vulputate interdum purus. Fusce ac erat purus. Proin lorem sem, convallis eget massa id, auctor commodo est. In eget neque condimentum, viverra augue ac, ultrices ligula. Praesent blandit nulla eleifend, efficitur nulla eu, porta arcu. Nullam sit amet odio vel massa pulvinar pretium. Suspendisse ac lectus est. Nulla ac maximus magna.

Praesent lacinia erat at felis posuere, sed fringilla libero finibus. Nam fermentum quam ac neque mollis, sit amet varius ante porttitor. Etiam vel venenatis metus, nec accumsan ex. Curabitur viverra ut lectus in sagittis. Aliquam neque eros, mattis in dictum in, scelerisque id felis. Nulla eu varius libero. Phasellus molestie risus id mauris suscipit varius. Donec molestie accumsan arcu, vitae imperdiet velit. In ac finibus sapien, porta aliquet diam. Morbi lobortis velit et ligula lacinia euismod.

Integer sit amet sodales nisl. Sed fermentum vel mauris a condimentum. Integer id erat aliquet, blandit augue ac, tincidunt mauris. Cras ac dictum augue, ac porttitor justo. In hac habitasse platea dictumst. Fusce leo sem, gravida eu mattis et, maximus sit amet urna. Sed condimentum ultricies purus, a convallis est tempus non. Nullam laoreet suscipit elit at consequat. Sed sit amet tempor velit. Mauris rhoncus turpis sed lectus tristique, a efficitur sapien placerat. In ex arcu, posuere eu libero eget, pharetra convallis magna. Donec pretium eget risus vulputate sollicitudin. Sed eget commodo nulla, nec hendrerit tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ullamcorper convallis tempor.

Morbi elementum eleifend ligula. Donec fermentum scelerisque hendrerit. Maecenas rhoncus lacinia libero, nec ultrices tellus tristique sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse potenti. Morbi eu urna ligula. Sed mi erat, ultricies ut purus at, pellentesque efficitur nisi. Aenean at erat sed eros tristique maximus. Quisque convallis lacus tempus mattis auctor. Aenean in massa id neque laoreet facilisis. Suspendisse potenti. Curabitur ac nisi eget orci hendrerit viverra nec quis purus. Maecenas euismod et lorem sit amet congue. Morbi et orci nibh. Quisque ut purus vitae massa facilisis aliquam.
EOT;
?>